apiVersion: v1
kind: Service
metadata:
  name: test-app-secrets-provider-init
  labels:
    app: test-app-secrets-provider-init
spec:
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  selector:
    app: test-app-secrets-provider-init
  type: {{ SERVICE_TYPE }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: test-app-secrets-provider-init
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: test-app-secrets-provider-init
  name: test-app-secrets-provider-init
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-app-secrets-provider-init
  template:
    metadata:
      labels:
        app: test-app-secrets-provider-init
    spec:
      serviceAccountName: test-app-secrets-provider-init
      containers:
      - image: {{ TEST_APP_DOCKER_IMAGE }}
        imagePullPolicy: {{ IMAGE_PULL_POLICY }}
        name: test-app
        ports:
        - name: http
          containerPort: 8080
        readinessProbe:
          httpGet:
            path: /pets
            port: http
          initialDelaySeconds: 15
          timeoutSeconds: 5
        env:
          - name: CONJUR_APPLIANCE_URL
            value: "{{ CONJUR_APPLIANCE_URL }}"
          - name: CONJUR_ACCOUNT
            value: {{ CONJUR_ACCOUNT }}
          - name: CONJUR_AUTHN_TOKEN_FILE
            value: /run/conjur/access-token
          - name: CONJUR_SSL_CERTIFICATE
            valueFrom:
              configMapKeyRef:
                name: {{ CONFIG_MAP_NAME }}
                key: ssl-certificate
        volumeMounts:
          - mountPath: /run/conjur
            name: conjur-access-token
            readOnly: true
      initContainers:
      - image: 'cyberark/secrets-provider-for-k8s:latest'
        imagePullPolicy: Always
        name: cyberark-secrets-provider-for-k8s
        env:
          - name: CONTAINER_MODE
            value: init

          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.name

          - name: MY_POD_NAMESPACE
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace

          - name: CONJUR_APPLIANCE_URL
            value: "{{ CONJUR_APPLIANCE_URL }}"

          - name: CONJUR_AUTHN_URL
            value: "{{ CONJUR_AUTHN_URL }}"

          - name: CONJUR_ACCOUNT
            value: {{ CONJUR_ACCOUNT }}

          - name: CONJUR_SSL_CERTIFICATE
            valueFrom:
              configMapKeyRef:
                name: {{ CONFIG_MAP_NAME }}
                key: ssl-certificate

          - name: K8S_SECRETS
            value: test-k8s-secret

          - name: SECRETS_DESTINATION
            value: k8s_secrets

          - name: DEBUG
            value: "true"

          - name: CONJUR_AUTHN_LOGIN
            value: "{{ CONJUR_AUTHN_LOGIN_PREFIX }}/test-app-secrets-provider-init"
      imagePullSecrets:
        - name: dockerpullsecret
      volumes:
        - name: conjur-access-token
          emptyDir:
            medium: Memory
