apiVersion: v1
kind: Secret
metadata:
  name: test-k8s-secret
type: Opaque
stringData:
  conjur-map: |-
    password: test-secrets-provider-init-app-db/password
    url: test-secrets-provider-init-app-db/url
    username: test-secrets-provider-init-app-db/
